apiVersion: robot.roboscale.io/v1alpha1
kind: MetricsCollector
metadata:
  labels:
    app.kubernetes.io/name: metricscollector
    app.kubernetes.io/instance: metricscollector-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: metricscollector-sample
spec:
  # TODO(user): Add fields here
