apiVersion: robot.roboscale.io/v1alpha1
kind: RobotVDI
metadata:
  labels:
    app.kubernetes.io/name: robotvdi
    app.kubernetes.io/instance: robotvdi-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: robotvdi-sample
spec:
  # TODO(user): Add fields here
