apiVersion: robot.roboscale.io/v1alpha1
kind: DiscoveryServer
metadata:
  labels:
    app.kubernetes.io/name: discoveryserver
    app.kubernetes.io/instance: discoveryserver-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: discoveryserver-sample
spec:
  # TODO(user): Add fields here
