apiVersion: robot.roboscale.io/v1alpha1
kind: ROSBridge
metadata:
  labels:
    app.kubernetes.io/name: rosbridge
    app.kubernetes.io/instance: rosbridge-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: rosbridge-sample
spec:
  # TODO(user): Add fields here
