apiVersion: robot.roboscale.io/v1alpha1
kind: BuildManager
metadata:
  labels:
    app.kubernetes.io/name: buildmanager
    app.kubernetes.io/instance: buildmanager-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: buildmanager-sample
spec:
  # TODO(user): Add fields here
