apiVersion: robot.roboscale.io/v1alpha1
kind: RobotArtifact
metadata:
  labels:
    app.kubernetes.io/name: robotartifact
    app.kubernetes.io/instance: robotartifact-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: robotartifact-sample
spec:
  # TODO(user): Add fields here
