apiVersion: robot.roboscale.io/v1alpha1
kind: RobotDevSuite
metadata:
  labels:
    app.kubernetes.io/name: robotdevsuite
    app.kubernetes.io/instance: robotdevsuite-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: robotdevsuite-sample
spec:
  # TODO(user): Add fields here
